INSERT INTO [dbo].[assignmentPerCoursePerStudent] ([studentid], [courseid], [assignmentid]) VALUES (1, 1, 6)
INSERT INTO [dbo].[assignmentPerCoursePerStudent] ([studentid], [courseid], [assignmentid]) VALUES (1, 3, 2)
INSERT INTO [dbo].[assignmentPerCoursePerStudent] ([studentid], [courseid], [assignmentid]) VALUES (2, 5, 1)
INSERT INTO [dbo].[assignmentPerCoursePerStudent] ([studentid], [courseid], [assignmentid]) VALUES (3, 1, 3)
INSERT INTO [dbo].[assignmentPerCoursePerStudent] ([studentid], [courseid], [assignmentid]) VALUES (4, 3, 2)
INSERT INTO [dbo].[assignmentPerCoursePerStudent] ([studentid], [courseid], [assignmentid]) VALUES (5, 1, 4)
INSERT INTO [dbo].[assignmentPerCoursePerStudent] ([studentid], [courseid], [assignmentid]) VALUES (5, 2, 1)
INSERT INTO [dbo].[assignmentPerCoursePerStudent] ([studentid], [courseid], [assignmentid]) VALUES (6, 5, 7)
